// Generated by LiveScript 1.2.0
(function(){
  var _, moment, fs, color, ref$, spawn, kill, __q, sh, os, shelljs, winston, debug, _module;
  _ = require('underscore');
  _.str = require('underscore.string');
  moment = require('moment');
  fs = require('fs');
  color = require('ansi-color').set;
  ref$ = require('child_process'), spawn = ref$.spawn, kill = ref$.kill;
  __q = require('q');
  sh = require('shelljs');
  os = require('os');
  shelljs = sh;
  winston = require('winston');
  debug = require('debug')('glp:sbarackquack');
  _.mixin(_.str.exports());
  _.str.include('Underscore.string', 'string');
  _module = function(){
    var taskSet, addTask, iface;
    taskSet = {};
    addTask = function(t, deps, cb){
      return taskSet[t] = {
        deps: deps,
        cb: cb
      };
    };
    iface = {
      addTask: addTask
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
